@echo off
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\client\messages\commands\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\client\anticheat\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\client\messages\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\client\status\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\net\channel\handler\*.java
A\*.java
A\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\net\channel\remote\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\net\login\handler\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\net\login\remote\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\net\world\guild\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\net\world\remote\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\net\channel\*.java
A\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\net\handler\*.java
A\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\net\login\*.java
A\*.java
A\*.java
A\*.java
A\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\net\mina\*.java
A\*.java
A\*.java
A\*.java
A\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\net\world\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\provider\wz\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\provider\xmlwz\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\scripting\event\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\scripting\npc\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\scripting\portal\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\scripting\quest\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\scripting\reactor\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\server\fourthjobquests\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\server\life\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\server\maps\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\server\movement\*.java
A\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\server\quest\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\tools\data\input\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\tools\data\output\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\tools\data\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
A\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\tools\performance\*.java
A\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\client\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\database\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\net\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\provider\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\scripting\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\server\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\tools\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\*.java
A\*.java
A\*.java
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\*.java
start win.bat
exit
