winrar a odinms.jarLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\client\messages\commands\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\client\anticheat\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\client\messages\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\client\status\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\net\channel\handler\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\net\channel\remote\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\net\login\handler\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\net\login\remote\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\net\world\guild\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\net\world\remote\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\net\channel\*.java\*.classLinRocks
A\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\net\handler\*.java\*.classLinRocks
A\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\net\login\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\net\mina\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\net\world\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\provider\wz\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\provider\xmlwz\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\scripting\event\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\scripting\npc\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\scripting\portal\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\scripting\quest\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\scripting\reactor\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\server\fourthjobquests\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\server\life\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\server\maps\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\server\movement\*.java\*.classLinRocks
A\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\server\quest\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\tools\data\input\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\tools\data\output\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\tools\data\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\tools\performance\*.java\*.classLinRocks
A\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\client\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\database\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\net\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\provider\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\scripting\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\server\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\tools\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\odinms\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\sf\*.java\*.classLinRocks
A\*.java\*.classLinRocks
A\*.java\*.classLinRocks
C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src\net\*.java\*.classLinRocks
echo Done
set here="C:\Users\David\Desktop\HurricaneMSv63\ValhallaStory\vms\trunk\src"
move odinms.jar ..
cd ..
move odinms.jar dist
cd src
start delete.bat
exit
